<?xml version="1.0" encoding="utf-8"?><Database Name="BEE" Class="LinqtoSQLDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-Q6VJ0TS\SQLEXPRESS;Initial Catalog=BEE;Persist Security Info=True;User ID=sa" SettingsObjectName="BEEACCOUNT.Properties.Settings" SettingsPropertyName="BEEConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.RptdetailSoCai" Member="RptdetailSoCais">
    <Type Name="RptdetailSoCai">
      <Column Name="username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Ngaychungtu" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="machungtu" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="diengiai" Type="System.String" DbType="NVarChar(225)" CanBeNull="true" />
      <Column Name="taikhoandoiung" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="psco" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="psno" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ton" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tblRpt_PhieuThu" Member="tblRpt_PhieuThus">
    <Type Name="tblRpt_PhieuThu">
      <Column Name="tencongty" Type="System.String" DbType="NVarChar(225)" CanBeNull="true" />
      <Column Name="diachicongty" Type="System.String" DbType="NVarChar(225)" CanBeNull="true" />
      <Column Name="masothue" Type="System.String" DbType="NVarChar(225)" CanBeNull="true" />
      <Column Name="tengiamdoc" Type="System.String" DbType="NVarChar(225)" CanBeNull="true" />
      <Column Name="tenketoantruong" Type="System.String" DbType="NVarChar(225)" CanBeNull="true" />
      <Column Name="sophieuthu" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ngaychungtu" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="nguoinoptien" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="nguoilapphieu" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="diachinguoinop" Type="System.String" DbType="NVarChar(225)" CanBeNull="true" />
      <Column Name="lydothu" Type="System.String" DbType="NVarChar(225)" CanBeNull="true" />
      <Column Name="sotien" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="sotienbangchu" Type="System.String" DbType="NVarChar(225)" CanBeNull="true" />
      <Column Name="sochungtugoc" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tkno" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="quyenso" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="tkco" Type="System.String" DbType="NVarChar(225)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.RptdetailSocaichitiet" Member="RptdetailSocaichitiets">
    <Type Name="RptdetailSocaichitiet">
      <Column Name="username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Ngaychungtu" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="machungtu" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="diengiai" Type="System.String" DbType="NVarChar(225)" CanBeNull="true" />
      <Column Name="taikhoandoiung" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="psco" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="psno" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ton" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.RptdetailSoQuy" Member="RptdetailSoQuys">
    <Type Name="RptdetailSoQuy">
      <Column Name="username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Ngaychungtu" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="machungtuthu" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="machungtuchi" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="diengiai" Type="System.String" DbType="NVarChar(225)" CanBeNull="true" />
      <Column Name="taikhoandoiung" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="psco" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="psno" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ton" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.RptdetaiNKC" Member="RptdetaiNKCs">
    <Type Name="RptdetaiNKC">
      <Column Name="username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Ngaychungtu" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="machungtu" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="diengiai" Type="System.String" DbType="NVarChar(225)" CanBeNull="true" />
      <Column Name="taikhoandoiung" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="psco" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="psno" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ton" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.RptdetaiTHchitiet" Member="RptdetaiTHchitiets">
    <Type Name="RptdetaiTHchitiet">
      <Column Name="username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="machitiet" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="tenchitiet" Type="System.String" DbType="NVarChar(225)" CanBeNull="true" />
      <Column Name="stt" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Nodk" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Codk" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Psno" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Psco" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Cock" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.RPtheadNKC" Member="RPtheadNKCs">
    <Type Name="RPtheadNKC">
      <Column Name="nam" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="giamdoc" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ketoantruong" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="nguoighiso" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="tencongty" Type="System.String" DbType="NVarChar(225)" CanBeNull="true" />
      <Column Name="masothue" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="diachicongty" Type="System.String" DbType="NVarChar(225)" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="taikhoan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.RPtheadSocai" Member="RPtheadSocais">
    <Type Name="RPtheadSocai">
      <Column Name="tungay" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="denngay" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="nodauky" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="codauky" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="psno" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="psco" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="cocuoiky" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="nocuoiky" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="tencongty" Type="System.String" DbType="NVarChar(225)" CanBeNull="true" />
      <Column Name="masothue" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="diachicongty" Type="System.String" DbType="NVarChar(225)" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="taikhoan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.RPtheadSocaichitiet" Member="RPtheadSocaichitiets">
    <Type Name="RPtheadSocaichitiet">
      <Column Name="tungay" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="denngay" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="nodauky" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="codauky" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="psno" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="psco" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="cocuoiky" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="nocuoiky" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="tencongty" Type="System.String" DbType="NVarChar(225)" CanBeNull="true" />
      <Column Name="masothue" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="diachicongty" Type="System.String" DbType="NVarChar(225)" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="taikhoan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="tenchitiettk" Type="System.String" DbType="NVarChar(225)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.RPtheadTHchitiet" Member="RPtheadTHchitiets">
    <Type Name="RPtheadTHchitiet">
      <Column Name="tencongty" Type="System.String" DbType="NVarChar(225)" CanBeNull="true" />
      <Column Name="masothue" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="diachicongty" Type="System.String" DbType="NVarChar(225)" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="taikhoan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="tungay" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="denngay" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.RPtsoQuy" Member="RPtsoQuys">
    <Type Name="RPtsoQuy">
      <Column Name="loaiquy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="tungay" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="denngay" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="nodauky" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="codauky" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="psno" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="psco" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="cocuoiky" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="nocuoiky" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="tencongty" Type="System.String" DbType="NVarChar(225)" CanBeNull="true" />
      <Column Name="masothue" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="diachicongty" Type="System.String" DbType="NVarChar(225)" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="taikhoan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_congty" Member="tbl_congties">
    <Type Name="tbl_congty">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tengiamdoc" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="diachicoty" Type="System.String" DbType="NVarChar(225)" CanBeNull="true" />
      <Column Name="tencongty" Type="System.String" DbType="NVarChar(225)" CanBeNull="true" />
      <Column Name="Masothue" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="chedoketoanapdung" Type="System.String" DbType="NVarChar(225)" CanBeNull="true" />
      <Column Name="tenketoantruong" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_ctkhachhang" Member="tbl_ctkhachhangs">
    <Type Name="tbl_ctkhachhang">
      <Column Name="Matk" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="NameTk" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="No" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Co" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SoduDk" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SoduCk" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SoduHT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Diengiai" Type="System.String" DbType="NChar(225)" CanBeNull="true" />
      <Column Name="SophuTK" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Sophu" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Ghichu" Type="System.String" DbType="NChar(225)" CanBeNull="true" />
      <Column Name="Ngayghiso" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Ngayctu" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SochitietTK" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Sochitiet" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Nghiepvuso" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_ctnganhang" Member="tbl_ctnganhangs">
    <Type Name="tbl_ctnganhang">
      <Column Name="Matk" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="NameTk" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="No" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Co" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SoduDk" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SoduCk" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SoduHT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Diengiai" Type="System.String" DbType="NChar(225)" CanBeNull="true" />
      <Column Name="SophuTK" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Sophu" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Ghichu" Type="System.String" DbType="NChar(225)" CanBeNull="true" />
      <Column Name="Ngayghiso" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Ngayctu" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SochitietTK" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Sochitiet" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Nghiepvuso" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_ctnhacungcap" Member="tbl_ctnhacungcaps">
    <Type Name="tbl_ctnhacungcap">
      <Column Name="Matk" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="NameTk" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="No" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Co" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SoduDk" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SoduCk" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SoduHT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Diengiai" Type="System.String" DbType="NChar(225)" CanBeNull="true" />
      <Column Name="SophuTK" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Sophu" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Ghichu" Type="System.String" DbType="NChar(225)" CanBeNull="true" />
      <Column Name="Ngayghiso" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Ngayctu" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SochitietTK" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Sochitiet" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Nghiepvuso" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_cttamung" Member="tbl_cttamungs">
    <Type Name="tbl_cttamung">
      <Column Name="Matk" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="NameTk" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="No" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Co" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SoduDk" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SoduCk" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SoduHT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Diengiai" Type="System.String" DbType="NChar(225)" CanBeNull="true" />
      <Column Name="SophuTK" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Sophu" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Ghichu" Type="System.String" DbType="NChar(225)" CanBeNull="true" />
      <Column Name="Ngayghiso" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Ngayctu" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SochitietTK" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Sochitiet" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Nghiepvuso" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Customer" Member="tbl_Customers">
    <Type Name="tbl_Customer">
      <Column Name="Customer" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SalesOrg" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="FullNameN" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Street" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="District" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Region" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Telephone1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PaymentTerms" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="PriceList" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="KeyAcc" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SalesDistrict" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ReconciliationAcct" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="VATregistrationNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CentralOrBlk" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OrBlk" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CTDescription" Type="System.String" DbType="NVarChar(225)" CanBeNull="true" />
      <Column Name="KANAME" Type="System.String" DbType="NVarChar(225)" CanBeNull="true" />
      <Column Name="UPDDAT" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="CCDescription" Type="System.String" DbType="NVarChar(225)" CanBeNull="true" />
      <Column Name="KAGROUP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CHN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BU" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Vendor" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Createdby" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Representative" Type="System.String" DbType="NVarChar(225)" CanBeNull="true" />
      <Column Name="Grpcode" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="SFAcode" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="SapCode" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="indirectCode" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="SALORG_CTR" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_dstaikhoan" Member="tbl_dstaikhoans">
    <Type Name="tbl_dstaikhoan">
      <Column Name="matk" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="tentk" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="captk" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="matktren" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="loaitkid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="loaichitiet" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="nodk" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="codk" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_loaitk" Member="tbl_loaitks">
    <Type Name="tbl_loaitk">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="idloaitk" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_machitiettk" Member="tbl_machitiettks">
    <Type Name="tbl_machitiettk">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tenchitiet" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="matk" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="machitiet" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ghichu" Type="System.String" DbType="NVarChar(225)" CanBeNull="true" />
      <Column Name="nodk" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="codk" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Socai" Member="tbl_Socais">
    <Type Name="tbl_Socai">
      <Column Name="Diengiai" Type="System.String" DbType="NChar(225)" CanBeNull="true" />
      <Column Name="Ngayghiso" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Ngayctu" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="manghiepvu" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="nghiepvuso" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="username" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="TkNo" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="TkCo" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="MaCTietTKCo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaCTietTKNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Kyhieuctu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Soctu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tenchitietCo" Type="System.String" DbType="NVarChar(225)" CanBeNull="true" />
      <Column Name="tenchitietNo" Type="System.String" DbType="NVarChar(225)" CanBeNull="true" />
      <Column Name="PsNo" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PsCo" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_SoQuy" Member="tbl_SoQuys">
    <Type Name="tbl_SoQuy">
      <Column Name="TKtienmat" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="ChitietTM" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ngayctu" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Sochungtu" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Machungtu" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="PsNo" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PsCo" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Diengiai" Type="System.String" DbType="NVarChar(225)" CanBeNull="true" />
      <Column Name="Chitietdoiung" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Nguoinopnhantien" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Diachinguoinhannop" Type="System.String" DbType="NVarChar(225)" CanBeNull="true" />
      <Column Name="Chungtugockemtheo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Ngayghiso" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="quyenso" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="TKdoiung" Type="System.String" DbType="NVarChar(225)" CanBeNull="true" />
      <Column Name="TenchitietTM" Type="System.String" DbType="NVarChar(225)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Temp" Member="tbl_Temps">
    <Type Name="tbl_Temp">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Version" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RegionCode" Type="System.String" DbType="NChar(225)" CanBeNull="true" />
      <Column Name="username" Type="System.String" DbType="NChar(225)" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="NChar(225)" CanBeNull="true" />
      <Column Name="userright" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="note" Type="System.String" DbType="NChar(225)" CanBeNull="true" />
      <Column Name="inputcontract" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>