#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEEACCOUNT
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BEE")]
	public partial class LinqtoSQLDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_ctkhachhang(tbl_ctkhachhang instance);
    partial void Updatetbl_ctkhachhang(tbl_ctkhachhang instance);
    partial void Deletetbl_ctkhachhang(tbl_ctkhachhang instance);
    partial void Inserttbl_Temp(tbl_Temp instance);
    partial void Updatetbl_Temp(tbl_Temp instance);
    partial void Deletetbl_Temp(tbl_Temp instance);
    partial void Inserttbl_ctnganhang(tbl_ctnganhang instance);
    partial void Updatetbl_ctnganhang(tbl_ctnganhang instance);
    partial void Deletetbl_ctnganhang(tbl_ctnganhang instance);
    partial void Inserttbl_ctnhacungcap(tbl_ctnhacungcap instance);
    partial void Updatetbl_ctnhacungcap(tbl_ctnhacungcap instance);
    partial void Deletetbl_ctnhacungcap(tbl_ctnhacungcap instance);
    partial void Inserttbl_cttamung(tbl_cttamung instance);
    partial void Updatetbl_cttamung(tbl_cttamung instance);
    partial void Deletetbl_cttamung(tbl_cttamung instance);
    partial void Inserttbl_Customer(tbl_Customer instance);
    partial void Updatetbl_Customer(tbl_Customer instance);
    partial void Deletetbl_Customer(tbl_Customer instance);
    partial void Inserttbl_dstaikhoan(tbl_dstaikhoan instance);
    partial void Updatetbl_dstaikhoan(tbl_dstaikhoan instance);
    partial void Deletetbl_dstaikhoan(tbl_dstaikhoan instance);
    partial void Inserttbl_loaitk(tbl_loaitk instance);
    partial void Updatetbl_loaitk(tbl_loaitk instance);
    partial void Deletetbl_loaitk(tbl_loaitk instance);
    partial void Inserttbl_Socai(tbl_Socai instance);
    partial void Updatetbl_Socai(tbl_Socai instance);
    partial void Deletetbl_Socai(tbl_Socai instance);
    #endregion
		
		public LinqtoSQLDataContext() : 
				base(global::BEEACCOUNT.Properties.Settings.Default.BEEConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LinqtoSQLDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqtoSQLDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqtoSQLDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqtoSQLDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_ctkhachhang> tbl_ctkhachhangs
		{
			get
			{
				return this.GetTable<tbl_ctkhachhang>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Temp> tbl_Temps
		{
			get
			{
				return this.GetTable<tbl_Temp>();
			}
		}
		
		public System.Data.Linq.Table<tbl_ctnganhang> tbl_ctnganhangs
		{
			get
			{
				return this.GetTable<tbl_ctnganhang>();
			}
		}
		
		public System.Data.Linq.Table<tbl_ctnhacungcap> tbl_ctnhacungcaps
		{
			get
			{
				return this.GetTable<tbl_ctnhacungcap>();
			}
		}
		
		public System.Data.Linq.Table<tbl_cttamung> tbl_cttamungs
		{
			get
			{
				return this.GetTable<tbl_cttamung>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Customer> tbl_Customers
		{
			get
			{
				return this.GetTable<tbl_Customer>();
			}
		}
		
		public System.Data.Linq.Table<tbl_dstaikhoan> tbl_dstaikhoans
		{
			get
			{
				return this.GetTable<tbl_dstaikhoan>();
			}
		}
		
		public System.Data.Linq.Table<tbl_loaitk> tbl_loaitks
		{
			get
			{
				return this.GetTable<tbl_loaitk>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Socai> tbl_Socais
		{
			get
			{
				return this.GetTable<tbl_Socai>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_ctkhachhang")]
	public partial class tbl_ctkhachhang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Matk;
		
		private string _NameTk;
		
		private System.Nullable<double> _No;
		
		private System.Nullable<double> _Co;
		
		private System.Nullable<double> _SoduDk;
		
		private System.Nullable<double> _SoduCk;
		
		private System.Nullable<double> _SoduHT;
		
		private string _Diengiai;
		
		private string _SophuTK;
		
		private bool _Sophu;
		
		private string _Ghichu;
		
		private System.Nullable<System.DateTime> _Ngayghiso;
		
		private System.Nullable<System.DateTime> _Ngayctu;
		
		private string _SochitietTK;
		
		private bool _Sochitiet;
		
		private System.Nullable<int> _Nghiepvuso;
		
		private int _id;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMatkChanging(string value);
    partial void OnMatkChanged();
    partial void OnNameTkChanging(string value);
    partial void OnNameTkChanged();
    partial void OnNoChanging(System.Nullable<double> value);
    partial void OnNoChanged();
    partial void OnCoChanging(System.Nullable<double> value);
    partial void OnCoChanged();
    partial void OnSoduDkChanging(System.Nullable<double> value);
    partial void OnSoduDkChanged();
    partial void OnSoduCkChanging(System.Nullable<double> value);
    partial void OnSoduCkChanged();
    partial void OnSoduHTChanging(System.Nullable<double> value);
    partial void OnSoduHTChanged();
    partial void OnDiengiaiChanging(string value);
    partial void OnDiengiaiChanged();
    partial void OnSophuTKChanging(string value);
    partial void OnSophuTKChanged();
    partial void OnSophuChanging(bool value);
    partial void OnSophuChanged();
    partial void OnGhichuChanging(string value);
    partial void OnGhichuChanged();
    partial void OnNgayghisoChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayghisoChanged();
    partial void OnNgayctuChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayctuChanged();
    partial void OnSochitietTKChanging(string value);
    partial void OnSochitietTKChanged();
    partial void OnSochitietChanging(bool value);
    partial void OnSochitietChanged();
    partial void OnNghiepvusoChanging(System.Nullable<int> value);
    partial void OnNghiepvusoChanged();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    #endregion
		
		public tbl_ctkhachhang()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matk", DbType="NChar(10)")]
		public string Matk
		{
			get
			{
				return this._Matk;
			}
			set
			{
				if ((this._Matk != value))
				{
					this.OnMatkChanging(value);
					this.SendPropertyChanging();
					this._Matk = value;
					this.SendPropertyChanged("Matk");
					this.OnMatkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameTk", DbType="NChar(50)")]
		public string NameTk
		{
			get
			{
				return this._NameTk;
			}
			set
			{
				if ((this._NameTk != value))
				{
					this.OnNameTkChanging(value);
					this.SendPropertyChanging();
					this._NameTk = value;
					this.SendPropertyChanged("NameTk");
					this.OnNameTkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_No", DbType="Float")]
		public System.Nullable<double> No
		{
			get
			{
				return this._No;
			}
			set
			{
				if ((this._No != value))
				{
					this.OnNoChanging(value);
					this.SendPropertyChanging();
					this._No = value;
					this.SendPropertyChanged("No");
					this.OnNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Co", DbType="Float")]
		public System.Nullable<double> Co
		{
			get
			{
				return this._Co;
			}
			set
			{
				if ((this._Co != value))
				{
					this.OnCoChanging(value);
					this.SendPropertyChanging();
					this._Co = value;
					this.SendPropertyChanged("Co");
					this.OnCoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoduDk", DbType="Float")]
		public System.Nullable<double> SoduDk
		{
			get
			{
				return this._SoduDk;
			}
			set
			{
				if ((this._SoduDk != value))
				{
					this.OnSoduDkChanging(value);
					this.SendPropertyChanging();
					this._SoduDk = value;
					this.SendPropertyChanged("SoduDk");
					this.OnSoduDkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoduCk", DbType="Float")]
		public System.Nullable<double> SoduCk
		{
			get
			{
				return this._SoduCk;
			}
			set
			{
				if ((this._SoduCk != value))
				{
					this.OnSoduCkChanging(value);
					this.SendPropertyChanging();
					this._SoduCk = value;
					this.SendPropertyChanged("SoduCk");
					this.OnSoduCkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoduHT", DbType="Float")]
		public System.Nullable<double> SoduHT
		{
			get
			{
				return this._SoduHT;
			}
			set
			{
				if ((this._SoduHT != value))
				{
					this.OnSoduHTChanging(value);
					this.SendPropertyChanging();
					this._SoduHT = value;
					this.SendPropertyChanged("SoduHT");
					this.OnSoduHTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Diengiai", DbType="NChar(225)")]
		public string Diengiai
		{
			get
			{
				return this._Diengiai;
			}
			set
			{
				if ((this._Diengiai != value))
				{
					this.OnDiengiaiChanging(value);
					this.SendPropertyChanging();
					this._Diengiai = value;
					this.SendPropertyChanged("Diengiai");
					this.OnDiengiaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SophuTK", DbType="NChar(10)")]
		public string SophuTK
		{
			get
			{
				return this._SophuTK;
			}
			set
			{
				if ((this._SophuTK != value))
				{
					this.OnSophuTKChanging(value);
					this.SendPropertyChanging();
					this._SophuTK = value;
					this.SendPropertyChanged("SophuTK");
					this.OnSophuTKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sophu", DbType="Bit NOT NULL")]
		public bool Sophu
		{
			get
			{
				return this._Sophu;
			}
			set
			{
				if ((this._Sophu != value))
				{
					this.OnSophuChanging(value);
					this.SendPropertyChanging();
					this._Sophu = value;
					this.SendPropertyChanged("Sophu");
					this.OnSophuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ghichu", DbType="NChar(225)")]
		public string Ghichu
		{
			get
			{
				return this._Ghichu;
			}
			set
			{
				if ((this._Ghichu != value))
				{
					this.OnGhichuChanging(value);
					this.SendPropertyChanging();
					this._Ghichu = value;
					this.SendPropertyChanged("Ghichu");
					this.OnGhichuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngayghiso", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ngayghiso
		{
			get
			{
				return this._Ngayghiso;
			}
			set
			{
				if ((this._Ngayghiso != value))
				{
					this.OnNgayghisoChanging(value);
					this.SendPropertyChanging();
					this._Ngayghiso = value;
					this.SendPropertyChanged("Ngayghiso");
					this.OnNgayghisoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngayctu", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ngayctu
		{
			get
			{
				return this._Ngayctu;
			}
			set
			{
				if ((this._Ngayctu != value))
				{
					this.OnNgayctuChanging(value);
					this.SendPropertyChanging();
					this._Ngayctu = value;
					this.SendPropertyChanged("Ngayctu");
					this.OnNgayctuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SochitietTK", DbType="NChar(10)")]
		public string SochitietTK
		{
			get
			{
				return this._SochitietTK;
			}
			set
			{
				if ((this._SochitietTK != value))
				{
					this.OnSochitietTKChanging(value);
					this.SendPropertyChanging();
					this._SochitietTK = value;
					this.SendPropertyChanged("SochitietTK");
					this.OnSochitietTKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sochitiet", DbType="Bit NOT NULL")]
		public bool Sochitiet
		{
			get
			{
				return this._Sochitiet;
			}
			set
			{
				if ((this._Sochitiet != value))
				{
					this.OnSochitietChanging(value);
					this.SendPropertyChanging();
					this._Sochitiet = value;
					this.SendPropertyChanged("Sochitiet");
					this.OnSochitietChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nghiepvuso", DbType="Int")]
		public System.Nullable<int> Nghiepvuso
		{
			get
			{
				return this._Nghiepvuso;
			}
			set
			{
				if ((this._Nghiepvuso != value))
				{
					this.OnNghiepvusoChanging(value);
					this.SendPropertyChanging();
					this._Nghiepvuso = value;
					this.SendPropertyChanged("Nghiepvuso");
					this.OnNghiepvusoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Temp")]
	public partial class tbl_Temp : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _Version;
		
		private string _RegionCode;
		
		private string _username;
		
		private string _password;
		
		private System.Nullable<int> _userright;
		
		private string _note;
		
		private bool _inputcontract;
		
		private bool _inputcontractconfirm;
		
		private bool _inputcontractfinalcontrol;
		
		private bool _paymentdisplay;
		
		private bool _paymentcreate;
		
		private bool _saleupdate;
		
		private bool _saleview;
		
		private bool _saledeleted;
		
		private bool _salechange;
		
		private bool _reports;
		
		private bool _masterdata;
		
		private bool _masterbegin;
		
		private bool _userssetup;
		
		private bool _pricingcheckview;
		
		private bool _pricingcheckupdate;
		
		private bool _masterdatafuction;
		
		private bool _changeitem;
		
		private bool _btaddnewItem;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnVersionChanging(System.Nullable<int> value);
    partial void OnVersionChanged();
    partial void OnRegionCodeChanging(string value);
    partial void OnRegionCodeChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnuserrightChanging(System.Nullable<int> value);
    partial void OnuserrightChanged();
    partial void OnnoteChanging(string value);
    partial void OnnoteChanged();
    partial void OninputcontractChanging(bool value);
    partial void OninputcontractChanged();
    partial void OninputcontractconfirmChanging(bool value);
    partial void OninputcontractconfirmChanged();
    partial void OninputcontractfinalcontrolChanging(bool value);
    partial void OninputcontractfinalcontrolChanged();
    partial void OnpaymentdisplayChanging(bool value);
    partial void OnpaymentdisplayChanged();
    partial void OnpaymentcreateChanging(bool value);
    partial void OnpaymentcreateChanged();
    partial void OnsaleupdateChanging(bool value);
    partial void OnsaleupdateChanged();
    partial void OnsaleviewChanging(bool value);
    partial void OnsaleviewChanged();
    partial void OnsaledeletedChanging(bool value);
    partial void OnsaledeletedChanged();
    partial void OnsalechangeChanging(bool value);
    partial void OnsalechangeChanged();
    partial void OnreportsChanging(bool value);
    partial void OnreportsChanged();
    partial void OnmasterdataChanging(bool value);
    partial void OnmasterdataChanged();
    partial void OnmasterbeginChanging(bool value);
    partial void OnmasterbeginChanged();
    partial void OnuserssetupChanging(bool value);
    partial void OnuserssetupChanged();
    partial void OnpricingcheckviewChanging(bool value);
    partial void OnpricingcheckviewChanged();
    partial void OnpricingcheckupdateChanging(bool value);
    partial void OnpricingcheckupdateChanged();
    partial void OnmasterdatafuctionChanging(bool value);
    partial void OnmasterdatafuctionChanged();
    partial void OnchangeitemChanging(bool value);
    partial void OnchangeitemChanged();
    partial void OnbtaddnewItemChanging(bool value);
    partial void OnbtaddnewItemChanged();
    #endregion
		
		public tbl_Temp()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Version", DbType="Int")]
		public System.Nullable<int> Version
		{
			get
			{
				return this._Version;
			}
			set
			{
				if ((this._Version != value))
				{
					this.OnVersionChanging(value);
					this.SendPropertyChanging();
					this._Version = value;
					this.SendPropertyChanged("Version");
					this.OnVersionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegionCode", DbType="NChar(225)")]
		public string RegionCode
		{
			get
			{
				return this._RegionCode;
			}
			set
			{
				if ((this._RegionCode != value))
				{
					this.OnRegionCodeChanging(value);
					this.SendPropertyChanging();
					this._RegionCode = value;
					this.SendPropertyChanged("RegionCode");
					this.OnRegionCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NChar(225)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NChar(225)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userright", DbType="Int")]
		public System.Nullable<int> userright
		{
			get
			{
				return this._userright;
			}
			set
			{
				if ((this._userright != value))
				{
					this.OnuserrightChanging(value);
					this.SendPropertyChanging();
					this._userright = value;
					this.SendPropertyChanged("userright");
					this.OnuserrightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_note", DbType="NChar(225)")]
		public string note
		{
			get
			{
				return this._note;
			}
			set
			{
				if ((this._note != value))
				{
					this.OnnoteChanging(value);
					this.SendPropertyChanging();
					this._note = value;
					this.SendPropertyChanged("note");
					this.OnnoteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_inputcontract", DbType="Bit NOT NULL")]
		public bool inputcontract
		{
			get
			{
				return this._inputcontract;
			}
			set
			{
				if ((this._inputcontract != value))
				{
					this.OninputcontractChanging(value);
					this.SendPropertyChanging();
					this._inputcontract = value;
					this.SendPropertyChanged("inputcontract");
					this.OninputcontractChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_inputcontractconfirm", DbType="Bit NOT NULL")]
		public bool inputcontractconfirm
		{
			get
			{
				return this._inputcontractconfirm;
			}
			set
			{
				if ((this._inputcontractconfirm != value))
				{
					this.OninputcontractconfirmChanging(value);
					this.SendPropertyChanging();
					this._inputcontractconfirm = value;
					this.SendPropertyChanged("inputcontractconfirm");
					this.OninputcontractconfirmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_inputcontractfinalcontrol", DbType="Bit NOT NULL")]
		public bool inputcontractfinalcontrol
		{
			get
			{
				return this._inputcontractfinalcontrol;
			}
			set
			{
				if ((this._inputcontractfinalcontrol != value))
				{
					this.OninputcontractfinalcontrolChanging(value);
					this.SendPropertyChanging();
					this._inputcontractfinalcontrol = value;
					this.SendPropertyChanged("inputcontractfinalcontrol");
					this.OninputcontractfinalcontrolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_paymentdisplay", DbType="Bit NOT NULL")]
		public bool paymentdisplay
		{
			get
			{
				return this._paymentdisplay;
			}
			set
			{
				if ((this._paymentdisplay != value))
				{
					this.OnpaymentdisplayChanging(value);
					this.SendPropertyChanging();
					this._paymentdisplay = value;
					this.SendPropertyChanged("paymentdisplay");
					this.OnpaymentdisplayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_paymentcreate", DbType="Bit NOT NULL")]
		public bool paymentcreate
		{
			get
			{
				return this._paymentcreate;
			}
			set
			{
				if ((this._paymentcreate != value))
				{
					this.OnpaymentcreateChanging(value);
					this.SendPropertyChanging();
					this._paymentcreate = value;
					this.SendPropertyChanged("paymentcreate");
					this.OnpaymentcreateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_saleupdate", DbType="Bit NOT NULL")]
		public bool saleupdate
		{
			get
			{
				return this._saleupdate;
			}
			set
			{
				if ((this._saleupdate != value))
				{
					this.OnsaleupdateChanging(value);
					this.SendPropertyChanging();
					this._saleupdate = value;
					this.SendPropertyChanged("saleupdate");
					this.OnsaleupdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_saleview", DbType="Bit NOT NULL")]
		public bool saleview
		{
			get
			{
				return this._saleview;
			}
			set
			{
				if ((this._saleview != value))
				{
					this.OnsaleviewChanging(value);
					this.SendPropertyChanging();
					this._saleview = value;
					this.SendPropertyChanged("saleview");
					this.OnsaleviewChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_saledeleted", DbType="Bit NOT NULL")]
		public bool saledeleted
		{
			get
			{
				return this._saledeleted;
			}
			set
			{
				if ((this._saledeleted != value))
				{
					this.OnsaledeletedChanging(value);
					this.SendPropertyChanging();
					this._saledeleted = value;
					this.SendPropertyChanged("saledeleted");
					this.OnsaledeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_salechange", DbType="Bit NOT NULL")]
		public bool salechange
		{
			get
			{
				return this._salechange;
			}
			set
			{
				if ((this._salechange != value))
				{
					this.OnsalechangeChanging(value);
					this.SendPropertyChanging();
					this._salechange = value;
					this.SendPropertyChanged("salechange");
					this.OnsalechangeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reports", DbType="Bit NOT NULL")]
		public bool reports
		{
			get
			{
				return this._reports;
			}
			set
			{
				if ((this._reports != value))
				{
					this.OnreportsChanging(value);
					this.SendPropertyChanging();
					this._reports = value;
					this.SendPropertyChanged("reports");
					this.OnreportsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_masterdata", DbType="Bit NOT NULL")]
		public bool masterdata
		{
			get
			{
				return this._masterdata;
			}
			set
			{
				if ((this._masterdata != value))
				{
					this.OnmasterdataChanging(value);
					this.SendPropertyChanging();
					this._masterdata = value;
					this.SendPropertyChanged("masterdata");
					this.OnmasterdataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_masterbegin", DbType="Bit NOT NULL")]
		public bool masterbegin
		{
			get
			{
				return this._masterbegin;
			}
			set
			{
				if ((this._masterbegin != value))
				{
					this.OnmasterbeginChanging(value);
					this.SendPropertyChanging();
					this._masterbegin = value;
					this.SendPropertyChanged("masterbegin");
					this.OnmasterbeginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userssetup", DbType="Bit NOT NULL")]
		public bool userssetup
		{
			get
			{
				return this._userssetup;
			}
			set
			{
				if ((this._userssetup != value))
				{
					this.OnuserssetupChanging(value);
					this.SendPropertyChanging();
					this._userssetup = value;
					this.SendPropertyChanged("userssetup");
					this.OnuserssetupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pricingcheckview", DbType="Bit NOT NULL")]
		public bool pricingcheckview
		{
			get
			{
				return this._pricingcheckview;
			}
			set
			{
				if ((this._pricingcheckview != value))
				{
					this.OnpricingcheckviewChanging(value);
					this.SendPropertyChanging();
					this._pricingcheckview = value;
					this.SendPropertyChanged("pricingcheckview");
					this.OnpricingcheckviewChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pricingcheckupdate", DbType="Bit NOT NULL")]
		public bool pricingcheckupdate
		{
			get
			{
				return this._pricingcheckupdate;
			}
			set
			{
				if ((this._pricingcheckupdate != value))
				{
					this.OnpricingcheckupdateChanging(value);
					this.SendPropertyChanging();
					this._pricingcheckupdate = value;
					this.SendPropertyChanged("pricingcheckupdate");
					this.OnpricingcheckupdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_masterdatafuction", DbType="Bit NOT NULL")]
		public bool masterdatafuction
		{
			get
			{
				return this._masterdatafuction;
			}
			set
			{
				if ((this._masterdatafuction != value))
				{
					this.OnmasterdatafuctionChanging(value);
					this.SendPropertyChanging();
					this._masterdatafuction = value;
					this.SendPropertyChanged("masterdatafuction");
					this.OnmasterdatafuctionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_changeitem", DbType="Bit NOT NULL")]
		public bool changeitem
		{
			get
			{
				return this._changeitem;
			}
			set
			{
				if ((this._changeitem != value))
				{
					this.OnchangeitemChanging(value);
					this.SendPropertyChanging();
					this._changeitem = value;
					this.SendPropertyChanged("changeitem");
					this.OnchangeitemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_btaddnewItem", DbType="Bit NOT NULL")]
		public bool btaddnewItem
		{
			get
			{
				return this._btaddnewItem;
			}
			set
			{
				if ((this._btaddnewItem != value))
				{
					this.OnbtaddnewItemChanging(value);
					this.SendPropertyChanging();
					this._btaddnewItem = value;
					this.SendPropertyChanged("btaddnewItem");
					this.OnbtaddnewItemChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_ctnganhang")]
	public partial class tbl_ctnganhang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Matk;
		
		private string _NameTk;
		
		private System.Nullable<double> _No;
		
		private System.Nullable<double> _Co;
		
		private System.Nullable<double> _SoduDk;
		
		private System.Nullable<double> _SoduCk;
		
		private System.Nullable<double> _SoduHT;
		
		private string _Diengiai;
		
		private string _SophuTK;
		
		private bool _Sophu;
		
		private string _Ghichu;
		
		private System.Nullable<System.DateTime> _Ngayghiso;
		
		private System.Nullable<System.DateTime> _Ngayctu;
		
		private string _SochitietTK;
		
		private bool _Sochitiet;
		
		private System.Nullable<int> _Nghiepvuso;
		
		private int _id;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMatkChanging(string value);
    partial void OnMatkChanged();
    partial void OnNameTkChanging(string value);
    partial void OnNameTkChanged();
    partial void OnNoChanging(System.Nullable<double> value);
    partial void OnNoChanged();
    partial void OnCoChanging(System.Nullable<double> value);
    partial void OnCoChanged();
    partial void OnSoduDkChanging(System.Nullable<double> value);
    partial void OnSoduDkChanged();
    partial void OnSoduCkChanging(System.Nullable<double> value);
    partial void OnSoduCkChanged();
    partial void OnSoduHTChanging(System.Nullable<double> value);
    partial void OnSoduHTChanged();
    partial void OnDiengiaiChanging(string value);
    partial void OnDiengiaiChanged();
    partial void OnSophuTKChanging(string value);
    partial void OnSophuTKChanged();
    partial void OnSophuChanging(bool value);
    partial void OnSophuChanged();
    partial void OnGhichuChanging(string value);
    partial void OnGhichuChanged();
    partial void OnNgayghisoChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayghisoChanged();
    partial void OnNgayctuChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayctuChanged();
    partial void OnSochitietTKChanging(string value);
    partial void OnSochitietTKChanged();
    partial void OnSochitietChanging(bool value);
    partial void OnSochitietChanged();
    partial void OnNghiepvusoChanging(System.Nullable<int> value);
    partial void OnNghiepvusoChanged();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    #endregion
		
		public tbl_ctnganhang()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matk", DbType="NChar(10)")]
		public string Matk
		{
			get
			{
				return this._Matk;
			}
			set
			{
				if ((this._Matk != value))
				{
					this.OnMatkChanging(value);
					this.SendPropertyChanging();
					this._Matk = value;
					this.SendPropertyChanged("Matk");
					this.OnMatkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameTk", DbType="NChar(50)")]
		public string NameTk
		{
			get
			{
				return this._NameTk;
			}
			set
			{
				if ((this._NameTk != value))
				{
					this.OnNameTkChanging(value);
					this.SendPropertyChanging();
					this._NameTk = value;
					this.SendPropertyChanged("NameTk");
					this.OnNameTkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_No", DbType="Float")]
		public System.Nullable<double> No
		{
			get
			{
				return this._No;
			}
			set
			{
				if ((this._No != value))
				{
					this.OnNoChanging(value);
					this.SendPropertyChanging();
					this._No = value;
					this.SendPropertyChanged("No");
					this.OnNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Co", DbType="Float")]
		public System.Nullable<double> Co
		{
			get
			{
				return this._Co;
			}
			set
			{
				if ((this._Co != value))
				{
					this.OnCoChanging(value);
					this.SendPropertyChanging();
					this._Co = value;
					this.SendPropertyChanged("Co");
					this.OnCoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoduDk", DbType="Float")]
		public System.Nullable<double> SoduDk
		{
			get
			{
				return this._SoduDk;
			}
			set
			{
				if ((this._SoduDk != value))
				{
					this.OnSoduDkChanging(value);
					this.SendPropertyChanging();
					this._SoduDk = value;
					this.SendPropertyChanged("SoduDk");
					this.OnSoduDkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoduCk", DbType="Float")]
		public System.Nullable<double> SoduCk
		{
			get
			{
				return this._SoduCk;
			}
			set
			{
				if ((this._SoduCk != value))
				{
					this.OnSoduCkChanging(value);
					this.SendPropertyChanging();
					this._SoduCk = value;
					this.SendPropertyChanged("SoduCk");
					this.OnSoduCkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoduHT", DbType="Float")]
		public System.Nullable<double> SoduHT
		{
			get
			{
				return this._SoduHT;
			}
			set
			{
				if ((this._SoduHT != value))
				{
					this.OnSoduHTChanging(value);
					this.SendPropertyChanging();
					this._SoduHT = value;
					this.SendPropertyChanged("SoduHT");
					this.OnSoduHTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Diengiai", DbType="NChar(225)")]
		public string Diengiai
		{
			get
			{
				return this._Diengiai;
			}
			set
			{
				if ((this._Diengiai != value))
				{
					this.OnDiengiaiChanging(value);
					this.SendPropertyChanging();
					this._Diengiai = value;
					this.SendPropertyChanged("Diengiai");
					this.OnDiengiaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SophuTK", DbType="NChar(10)")]
		public string SophuTK
		{
			get
			{
				return this._SophuTK;
			}
			set
			{
				if ((this._SophuTK != value))
				{
					this.OnSophuTKChanging(value);
					this.SendPropertyChanging();
					this._SophuTK = value;
					this.SendPropertyChanged("SophuTK");
					this.OnSophuTKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sophu", DbType="Bit NOT NULL")]
		public bool Sophu
		{
			get
			{
				return this._Sophu;
			}
			set
			{
				if ((this._Sophu != value))
				{
					this.OnSophuChanging(value);
					this.SendPropertyChanging();
					this._Sophu = value;
					this.SendPropertyChanged("Sophu");
					this.OnSophuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ghichu", DbType="NChar(225)")]
		public string Ghichu
		{
			get
			{
				return this._Ghichu;
			}
			set
			{
				if ((this._Ghichu != value))
				{
					this.OnGhichuChanging(value);
					this.SendPropertyChanging();
					this._Ghichu = value;
					this.SendPropertyChanged("Ghichu");
					this.OnGhichuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngayghiso", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ngayghiso
		{
			get
			{
				return this._Ngayghiso;
			}
			set
			{
				if ((this._Ngayghiso != value))
				{
					this.OnNgayghisoChanging(value);
					this.SendPropertyChanging();
					this._Ngayghiso = value;
					this.SendPropertyChanged("Ngayghiso");
					this.OnNgayghisoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngayctu", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ngayctu
		{
			get
			{
				return this._Ngayctu;
			}
			set
			{
				if ((this._Ngayctu != value))
				{
					this.OnNgayctuChanging(value);
					this.SendPropertyChanging();
					this._Ngayctu = value;
					this.SendPropertyChanged("Ngayctu");
					this.OnNgayctuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SochitietTK", DbType="NChar(10)")]
		public string SochitietTK
		{
			get
			{
				return this._SochitietTK;
			}
			set
			{
				if ((this._SochitietTK != value))
				{
					this.OnSochitietTKChanging(value);
					this.SendPropertyChanging();
					this._SochitietTK = value;
					this.SendPropertyChanged("SochitietTK");
					this.OnSochitietTKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sochitiet", DbType="Bit NOT NULL")]
		public bool Sochitiet
		{
			get
			{
				return this._Sochitiet;
			}
			set
			{
				if ((this._Sochitiet != value))
				{
					this.OnSochitietChanging(value);
					this.SendPropertyChanging();
					this._Sochitiet = value;
					this.SendPropertyChanged("Sochitiet");
					this.OnSochitietChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nghiepvuso", DbType="Int")]
		public System.Nullable<int> Nghiepvuso
		{
			get
			{
				return this._Nghiepvuso;
			}
			set
			{
				if ((this._Nghiepvuso != value))
				{
					this.OnNghiepvusoChanging(value);
					this.SendPropertyChanging();
					this._Nghiepvuso = value;
					this.SendPropertyChanged("Nghiepvuso");
					this.OnNghiepvusoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_ctnhacungcap")]
	public partial class tbl_ctnhacungcap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Matk;
		
		private string _NameTk;
		
		private System.Nullable<double> _No;
		
		private System.Nullable<double> _Co;
		
		private System.Nullable<double> _SoduDk;
		
		private System.Nullable<double> _SoduCk;
		
		private System.Nullable<double> _SoduHT;
		
		private string _Diengiai;
		
		private string _SophuTK;
		
		private bool _Sophu;
		
		private string _Ghichu;
		
		private System.Nullable<System.DateTime> _Ngayghiso;
		
		private System.Nullable<System.DateTime> _Ngayctu;
		
		private string _SochitietTK;
		
		private bool _Sochitiet;
		
		private System.Nullable<int> _Nghiepvuso;
		
		private int _id;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMatkChanging(string value);
    partial void OnMatkChanged();
    partial void OnNameTkChanging(string value);
    partial void OnNameTkChanged();
    partial void OnNoChanging(System.Nullable<double> value);
    partial void OnNoChanged();
    partial void OnCoChanging(System.Nullable<double> value);
    partial void OnCoChanged();
    partial void OnSoduDkChanging(System.Nullable<double> value);
    partial void OnSoduDkChanged();
    partial void OnSoduCkChanging(System.Nullable<double> value);
    partial void OnSoduCkChanged();
    partial void OnSoduHTChanging(System.Nullable<double> value);
    partial void OnSoduHTChanged();
    partial void OnDiengiaiChanging(string value);
    partial void OnDiengiaiChanged();
    partial void OnSophuTKChanging(string value);
    partial void OnSophuTKChanged();
    partial void OnSophuChanging(bool value);
    partial void OnSophuChanged();
    partial void OnGhichuChanging(string value);
    partial void OnGhichuChanged();
    partial void OnNgayghisoChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayghisoChanged();
    partial void OnNgayctuChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayctuChanged();
    partial void OnSochitietTKChanging(string value);
    partial void OnSochitietTKChanged();
    partial void OnSochitietChanging(bool value);
    partial void OnSochitietChanged();
    partial void OnNghiepvusoChanging(System.Nullable<int> value);
    partial void OnNghiepvusoChanged();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    #endregion
		
		public tbl_ctnhacungcap()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matk", DbType="NChar(10)")]
		public string Matk
		{
			get
			{
				return this._Matk;
			}
			set
			{
				if ((this._Matk != value))
				{
					this.OnMatkChanging(value);
					this.SendPropertyChanging();
					this._Matk = value;
					this.SendPropertyChanged("Matk");
					this.OnMatkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameTk", DbType="NChar(50)")]
		public string NameTk
		{
			get
			{
				return this._NameTk;
			}
			set
			{
				if ((this._NameTk != value))
				{
					this.OnNameTkChanging(value);
					this.SendPropertyChanging();
					this._NameTk = value;
					this.SendPropertyChanged("NameTk");
					this.OnNameTkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_No", DbType="Float")]
		public System.Nullable<double> No
		{
			get
			{
				return this._No;
			}
			set
			{
				if ((this._No != value))
				{
					this.OnNoChanging(value);
					this.SendPropertyChanging();
					this._No = value;
					this.SendPropertyChanged("No");
					this.OnNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Co", DbType="Float")]
		public System.Nullable<double> Co
		{
			get
			{
				return this._Co;
			}
			set
			{
				if ((this._Co != value))
				{
					this.OnCoChanging(value);
					this.SendPropertyChanging();
					this._Co = value;
					this.SendPropertyChanged("Co");
					this.OnCoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoduDk", DbType="Float")]
		public System.Nullable<double> SoduDk
		{
			get
			{
				return this._SoduDk;
			}
			set
			{
				if ((this._SoduDk != value))
				{
					this.OnSoduDkChanging(value);
					this.SendPropertyChanging();
					this._SoduDk = value;
					this.SendPropertyChanged("SoduDk");
					this.OnSoduDkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoduCk", DbType="Float")]
		public System.Nullable<double> SoduCk
		{
			get
			{
				return this._SoduCk;
			}
			set
			{
				if ((this._SoduCk != value))
				{
					this.OnSoduCkChanging(value);
					this.SendPropertyChanging();
					this._SoduCk = value;
					this.SendPropertyChanged("SoduCk");
					this.OnSoduCkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoduHT", DbType="Float")]
		public System.Nullable<double> SoduHT
		{
			get
			{
				return this._SoduHT;
			}
			set
			{
				if ((this._SoduHT != value))
				{
					this.OnSoduHTChanging(value);
					this.SendPropertyChanging();
					this._SoduHT = value;
					this.SendPropertyChanged("SoduHT");
					this.OnSoduHTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Diengiai", DbType="NChar(225)")]
		public string Diengiai
		{
			get
			{
				return this._Diengiai;
			}
			set
			{
				if ((this._Diengiai != value))
				{
					this.OnDiengiaiChanging(value);
					this.SendPropertyChanging();
					this._Diengiai = value;
					this.SendPropertyChanged("Diengiai");
					this.OnDiengiaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SophuTK", DbType="NChar(10)")]
		public string SophuTK
		{
			get
			{
				return this._SophuTK;
			}
			set
			{
				if ((this._SophuTK != value))
				{
					this.OnSophuTKChanging(value);
					this.SendPropertyChanging();
					this._SophuTK = value;
					this.SendPropertyChanged("SophuTK");
					this.OnSophuTKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sophu", DbType="Bit NOT NULL")]
		public bool Sophu
		{
			get
			{
				return this._Sophu;
			}
			set
			{
				if ((this._Sophu != value))
				{
					this.OnSophuChanging(value);
					this.SendPropertyChanging();
					this._Sophu = value;
					this.SendPropertyChanged("Sophu");
					this.OnSophuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ghichu", DbType="NChar(225)")]
		public string Ghichu
		{
			get
			{
				return this._Ghichu;
			}
			set
			{
				if ((this._Ghichu != value))
				{
					this.OnGhichuChanging(value);
					this.SendPropertyChanging();
					this._Ghichu = value;
					this.SendPropertyChanged("Ghichu");
					this.OnGhichuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngayghiso", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ngayghiso
		{
			get
			{
				return this._Ngayghiso;
			}
			set
			{
				if ((this._Ngayghiso != value))
				{
					this.OnNgayghisoChanging(value);
					this.SendPropertyChanging();
					this._Ngayghiso = value;
					this.SendPropertyChanged("Ngayghiso");
					this.OnNgayghisoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngayctu", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ngayctu
		{
			get
			{
				return this._Ngayctu;
			}
			set
			{
				if ((this._Ngayctu != value))
				{
					this.OnNgayctuChanging(value);
					this.SendPropertyChanging();
					this._Ngayctu = value;
					this.SendPropertyChanged("Ngayctu");
					this.OnNgayctuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SochitietTK", DbType="NChar(10)")]
		public string SochitietTK
		{
			get
			{
				return this._SochitietTK;
			}
			set
			{
				if ((this._SochitietTK != value))
				{
					this.OnSochitietTKChanging(value);
					this.SendPropertyChanging();
					this._SochitietTK = value;
					this.SendPropertyChanged("SochitietTK");
					this.OnSochitietTKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sochitiet", DbType="Bit NOT NULL")]
		public bool Sochitiet
		{
			get
			{
				return this._Sochitiet;
			}
			set
			{
				if ((this._Sochitiet != value))
				{
					this.OnSochitietChanging(value);
					this.SendPropertyChanging();
					this._Sochitiet = value;
					this.SendPropertyChanged("Sochitiet");
					this.OnSochitietChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nghiepvuso", DbType="Int")]
		public System.Nullable<int> Nghiepvuso
		{
			get
			{
				return this._Nghiepvuso;
			}
			set
			{
				if ((this._Nghiepvuso != value))
				{
					this.OnNghiepvusoChanging(value);
					this.SendPropertyChanging();
					this._Nghiepvuso = value;
					this.SendPropertyChanged("Nghiepvuso");
					this.OnNghiepvusoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_cttamung")]
	public partial class tbl_cttamung : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Matk;
		
		private string _NameTk;
		
		private System.Nullable<double> _No;
		
		private System.Nullable<double> _Co;
		
		private System.Nullable<double> _SoduDk;
		
		private System.Nullable<double> _SoduCk;
		
		private System.Nullable<double> _SoduHT;
		
		private string _Diengiai;
		
		private string _SophuTK;
		
		private bool _Sophu;
		
		private string _Ghichu;
		
		private System.Nullable<System.DateTime> _Ngayghiso;
		
		private System.Nullable<System.DateTime> _Ngayctu;
		
		private string _SochitietTK;
		
		private bool _Sochitiet;
		
		private System.Nullable<int> _Nghiepvuso;
		
		private int _id;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMatkChanging(string value);
    partial void OnMatkChanged();
    partial void OnNameTkChanging(string value);
    partial void OnNameTkChanged();
    partial void OnNoChanging(System.Nullable<double> value);
    partial void OnNoChanged();
    partial void OnCoChanging(System.Nullable<double> value);
    partial void OnCoChanged();
    partial void OnSoduDkChanging(System.Nullable<double> value);
    partial void OnSoduDkChanged();
    partial void OnSoduCkChanging(System.Nullable<double> value);
    partial void OnSoduCkChanged();
    partial void OnSoduHTChanging(System.Nullable<double> value);
    partial void OnSoduHTChanged();
    partial void OnDiengiaiChanging(string value);
    partial void OnDiengiaiChanged();
    partial void OnSophuTKChanging(string value);
    partial void OnSophuTKChanged();
    partial void OnSophuChanging(bool value);
    partial void OnSophuChanged();
    partial void OnGhichuChanging(string value);
    partial void OnGhichuChanged();
    partial void OnNgayghisoChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayghisoChanged();
    partial void OnNgayctuChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayctuChanged();
    partial void OnSochitietTKChanging(string value);
    partial void OnSochitietTKChanged();
    partial void OnSochitietChanging(bool value);
    partial void OnSochitietChanged();
    partial void OnNghiepvusoChanging(System.Nullable<int> value);
    partial void OnNghiepvusoChanged();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    #endregion
		
		public tbl_cttamung()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matk", DbType="NChar(10)")]
		public string Matk
		{
			get
			{
				return this._Matk;
			}
			set
			{
				if ((this._Matk != value))
				{
					this.OnMatkChanging(value);
					this.SendPropertyChanging();
					this._Matk = value;
					this.SendPropertyChanged("Matk");
					this.OnMatkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameTk", DbType="NChar(50)")]
		public string NameTk
		{
			get
			{
				return this._NameTk;
			}
			set
			{
				if ((this._NameTk != value))
				{
					this.OnNameTkChanging(value);
					this.SendPropertyChanging();
					this._NameTk = value;
					this.SendPropertyChanged("NameTk");
					this.OnNameTkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_No", DbType="Float")]
		public System.Nullable<double> No
		{
			get
			{
				return this._No;
			}
			set
			{
				if ((this._No != value))
				{
					this.OnNoChanging(value);
					this.SendPropertyChanging();
					this._No = value;
					this.SendPropertyChanged("No");
					this.OnNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Co", DbType="Float")]
		public System.Nullable<double> Co
		{
			get
			{
				return this._Co;
			}
			set
			{
				if ((this._Co != value))
				{
					this.OnCoChanging(value);
					this.SendPropertyChanging();
					this._Co = value;
					this.SendPropertyChanged("Co");
					this.OnCoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoduDk", DbType="Float")]
		public System.Nullable<double> SoduDk
		{
			get
			{
				return this._SoduDk;
			}
			set
			{
				if ((this._SoduDk != value))
				{
					this.OnSoduDkChanging(value);
					this.SendPropertyChanging();
					this._SoduDk = value;
					this.SendPropertyChanged("SoduDk");
					this.OnSoduDkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoduCk", DbType="Float")]
		public System.Nullable<double> SoduCk
		{
			get
			{
				return this._SoduCk;
			}
			set
			{
				if ((this._SoduCk != value))
				{
					this.OnSoduCkChanging(value);
					this.SendPropertyChanging();
					this._SoduCk = value;
					this.SendPropertyChanged("SoduCk");
					this.OnSoduCkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoduHT", DbType="Float")]
		public System.Nullable<double> SoduHT
		{
			get
			{
				return this._SoduHT;
			}
			set
			{
				if ((this._SoduHT != value))
				{
					this.OnSoduHTChanging(value);
					this.SendPropertyChanging();
					this._SoduHT = value;
					this.SendPropertyChanged("SoduHT");
					this.OnSoduHTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Diengiai", DbType="NChar(225)")]
		public string Diengiai
		{
			get
			{
				return this._Diengiai;
			}
			set
			{
				if ((this._Diengiai != value))
				{
					this.OnDiengiaiChanging(value);
					this.SendPropertyChanging();
					this._Diengiai = value;
					this.SendPropertyChanged("Diengiai");
					this.OnDiengiaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SophuTK", DbType="NChar(10)")]
		public string SophuTK
		{
			get
			{
				return this._SophuTK;
			}
			set
			{
				if ((this._SophuTK != value))
				{
					this.OnSophuTKChanging(value);
					this.SendPropertyChanging();
					this._SophuTK = value;
					this.SendPropertyChanged("SophuTK");
					this.OnSophuTKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sophu", DbType="Bit NOT NULL")]
		public bool Sophu
		{
			get
			{
				return this._Sophu;
			}
			set
			{
				if ((this._Sophu != value))
				{
					this.OnSophuChanging(value);
					this.SendPropertyChanging();
					this._Sophu = value;
					this.SendPropertyChanged("Sophu");
					this.OnSophuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ghichu", DbType="NChar(225)")]
		public string Ghichu
		{
			get
			{
				return this._Ghichu;
			}
			set
			{
				if ((this._Ghichu != value))
				{
					this.OnGhichuChanging(value);
					this.SendPropertyChanging();
					this._Ghichu = value;
					this.SendPropertyChanged("Ghichu");
					this.OnGhichuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngayghiso", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ngayghiso
		{
			get
			{
				return this._Ngayghiso;
			}
			set
			{
				if ((this._Ngayghiso != value))
				{
					this.OnNgayghisoChanging(value);
					this.SendPropertyChanging();
					this._Ngayghiso = value;
					this.SendPropertyChanged("Ngayghiso");
					this.OnNgayghisoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngayctu", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ngayctu
		{
			get
			{
				return this._Ngayctu;
			}
			set
			{
				if ((this._Ngayctu != value))
				{
					this.OnNgayctuChanging(value);
					this.SendPropertyChanging();
					this._Ngayctu = value;
					this.SendPropertyChanged("Ngayctu");
					this.OnNgayctuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SochitietTK", DbType="NChar(10)")]
		public string SochitietTK
		{
			get
			{
				return this._SochitietTK;
			}
			set
			{
				if ((this._SochitietTK != value))
				{
					this.OnSochitietTKChanging(value);
					this.SendPropertyChanging();
					this._SochitietTK = value;
					this.SendPropertyChanged("SochitietTK");
					this.OnSochitietTKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sochitiet", DbType="Bit NOT NULL")]
		public bool Sochitiet
		{
			get
			{
				return this._Sochitiet;
			}
			set
			{
				if ((this._Sochitiet != value))
				{
					this.OnSochitietChanging(value);
					this.SendPropertyChanging();
					this._Sochitiet = value;
					this.SendPropertyChanged("Sochitiet");
					this.OnSochitietChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nghiepvuso", DbType="Int")]
		public System.Nullable<int> Nghiepvuso
		{
			get
			{
				return this._Nghiepvuso;
			}
			set
			{
				if ((this._Nghiepvuso != value))
				{
					this.OnNghiepvusoChanging(value);
					this.SendPropertyChanging();
					this._Nghiepvuso = value;
					this.SendPropertyChanged("Nghiepvuso");
					this.OnNghiepvusoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Customer")]
	public partial class tbl_Customer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Nullable<double> _Customer;
		
		private string _SalesOrg;
		
		private string _FullNameN;
		
		private string _Street;
		
		private string _District;
		
		private string _City;
		
		private string _Region;
		
		private string _Telephone1;
		
		private int _id;
		
		private string _PaymentTerms;
		
		private string _PriceList;
		
		private string _KeyAcc;
		
		private string _SalesDistrict;
		
		private System.Nullable<System.DateTime> _CreatedOn;
		
		private string _ReconciliationAcct;
		
		private string _VATregistrationNo;
		
		private string _CentralOrBlk;
		
		private string _OrBlk;
		
		private string _CTDescription;
		
		private string _KANAME;
		
		private System.Nullable<System.DateTime> _UPDDAT;
		
		private string _CCDescription;
		
		private string _KAGROUP;
		
		private string _CHN;
		
		private string _BU;
		
		private string _Vendor;
		
		private string _Createdby;
		
		private string _Representative;
		
		private bool _Grpcode;
		
		private bool _SFAcode;
		
		private bool _SapCode;
		
		private bool _indirectCode;
		
		private string _SALORG_CTR;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCustomerChanging(System.Nullable<double> value);
    partial void OnCustomerChanged();
    partial void OnSalesOrgChanging(string value);
    partial void OnSalesOrgChanged();
    partial void OnFullNameNChanging(string value);
    partial void OnFullNameNChanged();
    partial void OnStreetChanging(string value);
    partial void OnStreetChanged();
    partial void OnDistrictChanging(string value);
    partial void OnDistrictChanged();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnRegionChanging(string value);
    partial void OnRegionChanged();
    partial void OnTelephone1Changing(string value);
    partial void OnTelephone1Changed();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnPaymentTermsChanging(string value);
    partial void OnPaymentTermsChanged();
    partial void OnPriceListChanging(string value);
    partial void OnPriceListChanged();
    partial void OnKeyAccChanging(string value);
    partial void OnKeyAccChanged();
    partial void OnSalesDistrictChanging(string value);
    partial void OnSalesDistrictChanged();
    partial void OnCreatedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedOnChanged();
    partial void OnReconciliationAcctChanging(string value);
    partial void OnReconciliationAcctChanged();
    partial void OnVATregistrationNoChanging(string value);
    partial void OnVATregistrationNoChanged();
    partial void OnCentralOrBlkChanging(string value);
    partial void OnCentralOrBlkChanged();
    partial void OnOrBlkChanging(string value);
    partial void OnOrBlkChanged();
    partial void OnCTDescriptionChanging(string value);
    partial void OnCTDescriptionChanged();
    partial void OnKANAMEChanging(string value);
    partial void OnKANAMEChanged();
    partial void OnUPDDATChanging(System.Nullable<System.DateTime> value);
    partial void OnUPDDATChanged();
    partial void OnCCDescriptionChanging(string value);
    partial void OnCCDescriptionChanged();
    partial void OnKAGROUPChanging(string value);
    partial void OnKAGROUPChanged();
    partial void OnCHNChanging(string value);
    partial void OnCHNChanged();
    partial void OnBUChanging(string value);
    partial void OnBUChanged();
    partial void OnVendorChanging(string value);
    partial void OnVendorChanged();
    partial void OnCreatedbyChanging(string value);
    partial void OnCreatedbyChanged();
    partial void OnRepresentativeChanging(string value);
    partial void OnRepresentativeChanged();
    partial void OnGrpcodeChanging(bool value);
    partial void OnGrpcodeChanged();
    partial void OnSFAcodeChanging(bool value);
    partial void OnSFAcodeChanged();
    partial void OnSapCodeChanging(bool value);
    partial void OnSapCodeChanged();
    partial void OnindirectCodeChanging(bool value);
    partial void OnindirectCodeChanged();
    partial void OnSALORG_CTRChanging(string value);
    partial void OnSALORG_CTRChanged();
    #endregion
		
		public tbl_Customer()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Customer", DbType="Float")]
		public System.Nullable<double> Customer
		{
			get
			{
				return this._Customer;
			}
			set
			{
				if ((this._Customer != value))
				{
					this.OnCustomerChanging(value);
					this.SendPropertyChanging();
					this._Customer = value;
					this.SendPropertyChanged("Customer");
					this.OnCustomerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalesOrg", DbType="NVarChar(10)")]
		public string SalesOrg
		{
			get
			{
				return this._SalesOrg;
			}
			set
			{
				if ((this._SalesOrg != value))
				{
					this.OnSalesOrgChanging(value);
					this.SendPropertyChanging();
					this._SalesOrg = value;
					this.SendPropertyChanged("SalesOrg");
					this.OnSalesOrgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullNameN", DbType="NVarChar(255)")]
		public string FullNameN
		{
			get
			{
				return this._FullNameN;
			}
			set
			{
				if ((this._FullNameN != value))
				{
					this.OnFullNameNChanging(value);
					this.SendPropertyChanging();
					this._FullNameN = value;
					this.SendPropertyChanged("FullNameN");
					this.OnFullNameNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Street", DbType="NVarChar(255)")]
		public string Street
		{
			get
			{
				return this._Street;
			}
			set
			{
				if ((this._Street != value))
				{
					this.OnStreetChanging(value);
					this.SendPropertyChanging();
					this._Street = value;
					this.SendPropertyChanged("Street");
					this.OnStreetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_District", DbType="NVarChar(255)")]
		public string District
		{
			get
			{
				return this._District;
			}
			set
			{
				if ((this._District != value))
				{
					this.OnDistrictChanging(value);
					this.SendPropertyChanging();
					this._District = value;
					this.SendPropertyChanged("District");
					this.OnDistrictChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="NVarChar(255)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this.OnCityChanging(value);
					this.SendPropertyChanging();
					this._City = value;
					this.SendPropertyChanged("City");
					this.OnCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Region", DbType="NVarChar(10)")]
		public string Region
		{
			get
			{
				return this._Region;
			}
			set
			{
				if ((this._Region != value))
				{
					this.OnRegionChanging(value);
					this.SendPropertyChanging();
					this._Region = value;
					this.SendPropertyChanged("Region");
					this.OnRegionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telephone1", DbType="NVarChar(50)")]
		public string Telephone1
		{
			get
			{
				return this._Telephone1;
			}
			set
			{
				if ((this._Telephone1 != value))
				{
					this.OnTelephone1Changing(value);
					this.SendPropertyChanging();
					this._Telephone1 = value;
					this.SendPropertyChanged("Telephone1");
					this.OnTelephone1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymentTerms", DbType="NChar(10)")]
		public string PaymentTerms
		{
			get
			{
				return this._PaymentTerms;
			}
			set
			{
				if ((this._PaymentTerms != value))
				{
					this.OnPaymentTermsChanging(value);
					this.SendPropertyChanging();
					this._PaymentTerms = value;
					this.SendPropertyChanged("PaymentTerms");
					this.OnPaymentTermsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PriceList", DbType="NChar(10)")]
		public string PriceList
		{
			get
			{
				return this._PriceList;
			}
			set
			{
				if ((this._PriceList != value))
				{
					this.OnPriceListChanging(value);
					this.SendPropertyChanging();
					this._PriceList = value;
					this.SendPropertyChanged("PriceList");
					this.OnPriceListChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeyAcc", DbType="NVarChar(50)")]
		public string KeyAcc
		{
			get
			{
				return this._KeyAcc;
			}
			set
			{
				if ((this._KeyAcc != value))
				{
					this.OnKeyAccChanging(value);
					this.SendPropertyChanging();
					this._KeyAcc = value;
					this.SendPropertyChanged("KeyAcc");
					this.OnKeyAccChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalesDistrict", DbType="NVarChar(50)")]
		public string SalesDistrict
		{
			get
			{
				return this._SalesDistrict;
			}
			set
			{
				if ((this._SalesDistrict != value))
				{
					this.OnSalesDistrictChanging(value);
					this.SendPropertyChanging();
					this._SalesDistrict = value;
					this.SendPropertyChanged("SalesDistrict");
					this.OnSalesDistrictChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedOn", DbType="Date")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this._CreatedOn;
			}
			set
			{
				if ((this._CreatedOn != value))
				{
					this.OnCreatedOnChanging(value);
					this.SendPropertyChanging();
					this._CreatedOn = value;
					this.SendPropertyChanged("CreatedOn");
					this.OnCreatedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReconciliationAcct", DbType="NVarChar(50)")]
		public string ReconciliationAcct
		{
			get
			{
				return this._ReconciliationAcct;
			}
			set
			{
				if ((this._ReconciliationAcct != value))
				{
					this.OnReconciliationAcctChanging(value);
					this.SendPropertyChanging();
					this._ReconciliationAcct = value;
					this.SendPropertyChanged("ReconciliationAcct");
					this.OnReconciliationAcctChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VATregistrationNo", DbType="NVarChar(50)")]
		public string VATregistrationNo
		{
			get
			{
				return this._VATregistrationNo;
			}
			set
			{
				if ((this._VATregistrationNo != value))
				{
					this.OnVATregistrationNoChanging(value);
					this.SendPropertyChanging();
					this._VATregistrationNo = value;
					this.SendPropertyChanged("VATregistrationNo");
					this.OnVATregistrationNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CentralOrBlk", DbType="NVarChar(50)")]
		public string CentralOrBlk
		{
			get
			{
				return this._CentralOrBlk;
			}
			set
			{
				if ((this._CentralOrBlk != value))
				{
					this.OnCentralOrBlkChanging(value);
					this.SendPropertyChanging();
					this._CentralOrBlk = value;
					this.SendPropertyChanged("CentralOrBlk");
					this.OnCentralOrBlkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrBlk", DbType="VarChar(50)")]
		public string OrBlk
		{
			get
			{
				return this._OrBlk;
			}
			set
			{
				if ((this._OrBlk != value))
				{
					this.OnOrBlkChanging(value);
					this.SendPropertyChanging();
					this._OrBlk = value;
					this.SendPropertyChanged("OrBlk");
					this.OnOrBlkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CTDescription", DbType="NVarChar(225)")]
		public string CTDescription
		{
			get
			{
				return this._CTDescription;
			}
			set
			{
				if ((this._CTDescription != value))
				{
					this.OnCTDescriptionChanging(value);
					this.SendPropertyChanging();
					this._CTDescription = value;
					this.SendPropertyChanged("CTDescription");
					this.OnCTDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KANAME", DbType="NVarChar(225)")]
		public string KANAME
		{
			get
			{
				return this._KANAME;
			}
			set
			{
				if ((this._KANAME != value))
				{
					this.OnKANAMEChanging(value);
					this.SendPropertyChanging();
					this._KANAME = value;
					this.SendPropertyChanged("KANAME");
					this.OnKANAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPDDAT", DbType="Date")]
		public System.Nullable<System.DateTime> UPDDAT
		{
			get
			{
				return this._UPDDAT;
			}
			set
			{
				if ((this._UPDDAT != value))
				{
					this.OnUPDDATChanging(value);
					this.SendPropertyChanging();
					this._UPDDAT = value;
					this.SendPropertyChanged("UPDDAT");
					this.OnUPDDATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CCDescription", DbType="NVarChar(225)")]
		public string CCDescription
		{
			get
			{
				return this._CCDescription;
			}
			set
			{
				if ((this._CCDescription != value))
				{
					this.OnCCDescriptionChanging(value);
					this.SendPropertyChanging();
					this._CCDescription = value;
					this.SendPropertyChanged("CCDescription");
					this.OnCCDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KAGROUP", DbType="NVarChar(50)")]
		public string KAGROUP
		{
			get
			{
				return this._KAGROUP;
			}
			set
			{
				if ((this._KAGROUP != value))
				{
					this.OnKAGROUPChanging(value);
					this.SendPropertyChanging();
					this._KAGROUP = value;
					this.SendPropertyChanged("KAGROUP");
					this.OnKAGROUPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHN", DbType="NVarChar(50)")]
		public string CHN
		{
			get
			{
				return this._CHN;
			}
			set
			{
				if ((this._CHN != value))
				{
					this.OnCHNChanging(value);
					this.SendPropertyChanging();
					this._CHN = value;
					this.SendPropertyChanged("CHN");
					this.OnCHNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BU", DbType="NVarChar(50)")]
		public string BU
		{
			get
			{
				return this._BU;
			}
			set
			{
				if ((this._BU != value))
				{
					this.OnBUChanging(value);
					this.SendPropertyChanging();
					this._BU = value;
					this.SendPropertyChanged("BU");
					this.OnBUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vendor", DbType="NVarChar(50)")]
		public string Vendor
		{
			get
			{
				return this._Vendor;
			}
			set
			{
				if ((this._Vendor != value))
				{
					this.OnVendorChanging(value);
					this.SendPropertyChanging();
					this._Vendor = value;
					this.SendPropertyChanged("Vendor");
					this.OnVendorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Createdby", DbType="NVarChar(50)")]
		public string Createdby
		{
			get
			{
				return this._Createdby;
			}
			set
			{
				if ((this._Createdby != value))
				{
					this.OnCreatedbyChanging(value);
					this.SendPropertyChanging();
					this._Createdby = value;
					this.SendPropertyChanged("Createdby");
					this.OnCreatedbyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Representative", DbType="NVarChar(225)")]
		public string Representative
		{
			get
			{
				return this._Representative;
			}
			set
			{
				if ((this._Representative != value))
				{
					this.OnRepresentativeChanging(value);
					this.SendPropertyChanging();
					this._Representative = value;
					this.SendPropertyChanged("Representative");
					this.OnRepresentativeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Grpcode", DbType="Bit NOT NULL")]
		public bool Grpcode
		{
			get
			{
				return this._Grpcode;
			}
			set
			{
				if ((this._Grpcode != value))
				{
					this.OnGrpcodeChanging(value);
					this.SendPropertyChanging();
					this._Grpcode = value;
					this.SendPropertyChanged("Grpcode");
					this.OnGrpcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SFAcode", DbType="Bit NOT NULL")]
		public bool SFAcode
		{
			get
			{
				return this._SFAcode;
			}
			set
			{
				if ((this._SFAcode != value))
				{
					this.OnSFAcodeChanging(value);
					this.SendPropertyChanging();
					this._SFAcode = value;
					this.SendPropertyChanged("SFAcode");
					this.OnSFAcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SapCode", DbType="Bit NOT NULL")]
		public bool SapCode
		{
			get
			{
				return this._SapCode;
			}
			set
			{
				if ((this._SapCode != value))
				{
					this.OnSapCodeChanging(value);
					this.SendPropertyChanging();
					this._SapCode = value;
					this.SendPropertyChanged("SapCode");
					this.OnSapCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_indirectCode", DbType="Bit NOT NULL")]
		public bool indirectCode
		{
			get
			{
				return this._indirectCode;
			}
			set
			{
				if ((this._indirectCode != value))
				{
					this.OnindirectCodeChanging(value);
					this.SendPropertyChanging();
					this._indirectCode = value;
					this.SendPropertyChanged("indirectCode");
					this.OnindirectCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SALORG_CTR", DbType="NChar(10)")]
		public string SALORG_CTR
		{
			get
			{
				return this._SALORG_CTR;
			}
			set
			{
				if ((this._SALORG_CTR != value))
				{
					this.OnSALORG_CTRChanging(value);
					this.SendPropertyChanging();
					this._SALORG_CTR = value;
					this.SendPropertyChanged("SALORG_CTR");
					this.OnSALORG_CTRChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_dstaikhoan")]
	public partial class tbl_dstaikhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _matk;
		
		private string _tentk;
		
		private int _id;
		
		private int _captk;
		
		private string _matktren;
		
		private System.Nullable<int> _loaitkid;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmatkChanging(string value);
    partial void OnmatkChanged();
    partial void OntentkChanging(string value);
    partial void OntentkChanged();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OncaptkChanging(int value);
    partial void OncaptkChanged();
    partial void OnmatktrenChanging(string value);
    partial void OnmatktrenChanged();
    partial void OnloaitkidChanging(System.Nullable<int> value);
    partial void OnloaitkidChanged();
    #endregion
		
		public tbl_dstaikhoan()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matk", DbType="NChar(10)")]
		public string matk
		{
			get
			{
				return this._matk;
			}
			set
			{
				if ((this._matk != value))
				{
					this.OnmatkChanging(value);
					this.SendPropertyChanging();
					this._matk = value;
					this.SendPropertyChanged("matk");
					this.OnmatkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tentk", DbType="NChar(50)")]
		public string tentk
		{
			get
			{
				return this._tentk;
			}
			set
			{
				if ((this._tentk != value))
				{
					this.OntentkChanging(value);
					this.SendPropertyChanging();
					this._tentk = value;
					this.SendPropertyChanged("tentk");
					this.OntentkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_captk", DbType="Int NOT NULL")]
		public int captk
		{
			get
			{
				return this._captk;
			}
			set
			{
				if ((this._captk != value))
				{
					this.OncaptkChanging(value);
					this.SendPropertyChanging();
					this._captk = value;
					this.SendPropertyChanged("captk");
					this.OncaptkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matktren", DbType="NChar(10)")]
		public string matktren
		{
			get
			{
				return this._matktren;
			}
			set
			{
				if ((this._matktren != value))
				{
					this.OnmatktrenChanging(value);
					this.SendPropertyChanging();
					this._matktren = value;
					this.SendPropertyChanged("matktren");
					this.OnmatktrenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loaitkid", DbType="Int")]
		public System.Nullable<int> loaitkid
		{
			get
			{
				return this._loaitkid;
			}
			set
			{
				if ((this._loaitkid != value))
				{
					this.OnloaitkidChanging(value);
					this.SendPropertyChanging();
					this._loaitkid = value;
					this.SendPropertyChanged("loaitkid");
					this.OnloaitkidChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_loaitk")]
	public partial class tbl_loaitk : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idloaitk;
		
		private string _name;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidloaitkChanging(int value);
    partial void OnidloaitkChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    #endregion
		
		public tbl_loaitk()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idloaitk", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idloaitk
		{
			get
			{
				return this._idloaitk;
			}
			set
			{
				if ((this._idloaitk != value))
				{
					this.OnidloaitkChanging(value);
					this.SendPropertyChanging();
					this._idloaitk = value;
					this.SendPropertyChanged("idloaitk");
					this.OnidloaitkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Socai")]
	public partial class tbl_Socai : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Matk;
		
		private string _NameTk;
		
		private System.Nullable<double> _No;
		
		private System.Nullable<double> _Co;
		
		private System.Nullable<double> _SoduDk;
		
		private System.Nullable<double> _SoduCk;
		
		private System.Nullable<double> _SoduHT;
		
		private string _Diengiai;
		
		private string _SophuTK;
		
		private bool _Sophu;
		
		private string _Ghichu;
		
		private System.Nullable<System.DateTime> _Ngayghiso;
		
		private System.Nullable<System.DateTime> _Ngayctu;
		
		private string _SochitietTK;
		
		private bool _Sochitiet;
		
		private System.Nullable<int> _Nghiepvuso;
		
		private int _id;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMatkChanging(string value);
    partial void OnMatkChanged();
    partial void OnNameTkChanging(string value);
    partial void OnNameTkChanged();
    partial void OnNoChanging(System.Nullable<double> value);
    partial void OnNoChanged();
    partial void OnCoChanging(System.Nullable<double> value);
    partial void OnCoChanged();
    partial void OnSoduDkChanging(System.Nullable<double> value);
    partial void OnSoduDkChanged();
    partial void OnSoduCkChanging(System.Nullable<double> value);
    partial void OnSoduCkChanged();
    partial void OnSoduHTChanging(System.Nullable<double> value);
    partial void OnSoduHTChanged();
    partial void OnDiengiaiChanging(string value);
    partial void OnDiengiaiChanged();
    partial void OnSophuTKChanging(string value);
    partial void OnSophuTKChanged();
    partial void OnSophuChanging(bool value);
    partial void OnSophuChanged();
    partial void OnGhichuChanging(string value);
    partial void OnGhichuChanged();
    partial void OnNgayghisoChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayghisoChanged();
    partial void OnNgayctuChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayctuChanged();
    partial void OnSochitietTKChanging(string value);
    partial void OnSochitietTKChanged();
    partial void OnSochitietChanging(bool value);
    partial void OnSochitietChanged();
    partial void OnNghiepvusoChanging(System.Nullable<int> value);
    partial void OnNghiepvusoChanged();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    #endregion
		
		public tbl_Socai()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matk", DbType="NChar(10)")]
		public string Matk
		{
			get
			{
				return this._Matk;
			}
			set
			{
				if ((this._Matk != value))
				{
					this.OnMatkChanging(value);
					this.SendPropertyChanging();
					this._Matk = value;
					this.SendPropertyChanged("Matk");
					this.OnMatkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameTk", DbType="NChar(50)")]
		public string NameTk
		{
			get
			{
				return this._NameTk;
			}
			set
			{
				if ((this._NameTk != value))
				{
					this.OnNameTkChanging(value);
					this.SendPropertyChanging();
					this._NameTk = value;
					this.SendPropertyChanged("NameTk");
					this.OnNameTkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_No", DbType="Float")]
		public System.Nullable<double> No
		{
			get
			{
				return this._No;
			}
			set
			{
				if ((this._No != value))
				{
					this.OnNoChanging(value);
					this.SendPropertyChanging();
					this._No = value;
					this.SendPropertyChanged("No");
					this.OnNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Co", DbType="Float")]
		public System.Nullable<double> Co
		{
			get
			{
				return this._Co;
			}
			set
			{
				if ((this._Co != value))
				{
					this.OnCoChanging(value);
					this.SendPropertyChanging();
					this._Co = value;
					this.SendPropertyChanged("Co");
					this.OnCoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoduDk", DbType="Float")]
		public System.Nullable<double> SoduDk
		{
			get
			{
				return this._SoduDk;
			}
			set
			{
				if ((this._SoduDk != value))
				{
					this.OnSoduDkChanging(value);
					this.SendPropertyChanging();
					this._SoduDk = value;
					this.SendPropertyChanged("SoduDk");
					this.OnSoduDkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoduCk", DbType="Float")]
		public System.Nullable<double> SoduCk
		{
			get
			{
				return this._SoduCk;
			}
			set
			{
				if ((this._SoduCk != value))
				{
					this.OnSoduCkChanging(value);
					this.SendPropertyChanging();
					this._SoduCk = value;
					this.SendPropertyChanged("SoduCk");
					this.OnSoduCkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoduHT", DbType="Float")]
		public System.Nullable<double> SoduHT
		{
			get
			{
				return this._SoduHT;
			}
			set
			{
				if ((this._SoduHT != value))
				{
					this.OnSoduHTChanging(value);
					this.SendPropertyChanging();
					this._SoduHT = value;
					this.SendPropertyChanged("SoduHT");
					this.OnSoduHTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Diengiai", DbType="NChar(225)")]
		public string Diengiai
		{
			get
			{
				return this._Diengiai;
			}
			set
			{
				if ((this._Diengiai != value))
				{
					this.OnDiengiaiChanging(value);
					this.SendPropertyChanging();
					this._Diengiai = value;
					this.SendPropertyChanged("Diengiai");
					this.OnDiengiaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SophuTK", DbType="NChar(10)")]
		public string SophuTK
		{
			get
			{
				return this._SophuTK;
			}
			set
			{
				if ((this._SophuTK != value))
				{
					this.OnSophuTKChanging(value);
					this.SendPropertyChanging();
					this._SophuTK = value;
					this.SendPropertyChanged("SophuTK");
					this.OnSophuTKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sophu", DbType="Bit NOT NULL")]
		public bool Sophu
		{
			get
			{
				return this._Sophu;
			}
			set
			{
				if ((this._Sophu != value))
				{
					this.OnSophuChanging(value);
					this.SendPropertyChanging();
					this._Sophu = value;
					this.SendPropertyChanged("Sophu");
					this.OnSophuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ghichu", DbType="NChar(225)")]
		public string Ghichu
		{
			get
			{
				return this._Ghichu;
			}
			set
			{
				if ((this._Ghichu != value))
				{
					this.OnGhichuChanging(value);
					this.SendPropertyChanging();
					this._Ghichu = value;
					this.SendPropertyChanged("Ghichu");
					this.OnGhichuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngayghiso", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ngayghiso
		{
			get
			{
				return this._Ngayghiso;
			}
			set
			{
				if ((this._Ngayghiso != value))
				{
					this.OnNgayghisoChanging(value);
					this.SendPropertyChanging();
					this._Ngayghiso = value;
					this.SendPropertyChanged("Ngayghiso");
					this.OnNgayghisoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngayctu", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ngayctu
		{
			get
			{
				return this._Ngayctu;
			}
			set
			{
				if ((this._Ngayctu != value))
				{
					this.OnNgayctuChanging(value);
					this.SendPropertyChanging();
					this._Ngayctu = value;
					this.SendPropertyChanged("Ngayctu");
					this.OnNgayctuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SochitietTK", DbType="NChar(10)")]
		public string SochitietTK
		{
			get
			{
				return this._SochitietTK;
			}
			set
			{
				if ((this._SochitietTK != value))
				{
					this.OnSochitietTKChanging(value);
					this.SendPropertyChanging();
					this._SochitietTK = value;
					this.SendPropertyChanged("SochitietTK");
					this.OnSochitietTKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sochitiet", DbType="Bit NOT NULL")]
		public bool Sochitiet
		{
			get
			{
				return this._Sochitiet;
			}
			set
			{
				if ((this._Sochitiet != value))
				{
					this.OnSochitietChanging(value);
					this.SendPropertyChanging();
					this._Sochitiet = value;
					this.SendPropertyChanged("Sochitiet");
					this.OnSochitietChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nghiepvuso", DbType="Int")]
		public System.Nullable<int> Nghiepvuso
		{
			get
			{
				return this._Nghiepvuso;
			}
			set
			{
				if ((this._Nghiepvuso != value))
				{
					this.OnNghiepvusoChanging(value);
					this.SendPropertyChanging();
					this._Nghiepvuso = value;
					this.SendPropertyChanged("Nghiepvuso");
					this.OnNghiepvusoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
